
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 10 10:47:17 GMT-03:00 2015
//----------------------------------------------------

package sintatico;

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Nov 10 10:47:17 GMT-03:00 2015
  */
public class RubyParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public RubyParser() {super();}

  /** Constructor which sets the default scanner. */
  public RubyParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public RubyParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\024\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\004\000\002\003\004\000\002\003\004" +
    "\000\002\003\002\000\002\004\007\000\002\005\006\000" +
    "\002\005\004\000\002\005\002\000\002\011\006\000\002" +
    "\013\007\000\002\006\005\000\002\006\005\000\002\012" +
    "\007\000\002\007\003\000\002\007\003\000\002\010\005" +
    "\000\002\010\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\060\000\016\002\ufffb\043\006\044\005\047\012\130" +
    "\015\133\011\001\002\000\024\002\ufffb\025\ufffb\032\ufffb" +
    "\043\006\044\005\047\012\050\ufffb\130\015\133\011\001" +
    "\002\000\006\127\023\130\025\001\002\000\004\130\047" +
    "\001\002\000\024\002\ufffb\025\ufffb\032\ufffb\043\006\044" +
    "\005\047\012\050\ufffb\130\015\133\011\001\002\000\004" +
    "\002\044\001\002\000\024\002\uffee\025\uffee\032\uffee\043" +
    "\uffee\044\uffee\047\uffee\050\uffee\130\uffee\133\uffee\001\002" +
    "\000\006\127\023\130\025\001\002\000\004\002\001\001" +
    "\002\000\024\002\ufffb\025\ufffb\032\ufffb\043\006\044\005" +
    "\047\012\050\ufffb\130\015\133\011\001\002\000\004\110" +
    "\020\001\002\000\024\002\ufffb\025\ufffb\032\ufffb\043\006" +
    "\044\005\047\012\050\ufffb\130\015\133\011\001\002\000" +
    "\012\002\uffff\025\uffff\032\uffff\050\uffff\001\002\000\004" +
    "\127\021\001\002\000\024\002\uffef\025\uffef\032\uffef\043" +
    "\uffef\044\uffef\047\uffef\050\uffef\130\uffef\133\uffef\001\002" +
    "\000\012\002\ufffc\025\ufffc\032\ufffc\050\ufffc\001\002\000" +
    "\030\025\ufff0\032\ufff0\043\ufff0\044\ufff0\046\ufff0\047\ufff0" +
    "\050\ufff0\073\ufff0\074\ufff0\130\ufff0\133\ufff0\001\002\000" +
    "\006\073\041\074\040\001\002\000\030\025\ufff1\032\ufff1" +
    "\043\ufff1\044\ufff1\046\ufff1\047\ufff1\050\ufff1\073\ufff1\074" +
    "\ufff1\130\ufff1\133\ufff1\001\002\000\022\025\ufffb\032\ufffb" +
    "\043\006\044\005\047\012\050\ufffb\130\015\133\011\001" +
    "\002\000\010\025\030\032\031\050\ufff7\001\002\000\016" +
    "\043\006\044\005\047\012\050\ufffb\130\015\133\011\001" +
    "\002\000\006\127\023\130\025\001\002\000\004\050\033" +
    "\001\002\000\024\002\ufffa\025\ufffa\032\ufffa\043\ufffa\044" +
    "\ufffa\047\ufffa\050\ufffa\130\ufffa\133\ufffa\001\002\000\022" +
    "\025\ufffb\032\ufffb\043\006\044\005\047\012\050\ufffb\130" +
    "\015\133\011\001\002\000\010\025\030\032\031\050\ufff7" +
    "\001\002\000\004\050\ufff9\001\002\000\004\050\ufff8\001" +
    "\002\000\006\127\023\130\025\001\002\000\006\127\023" +
    "\130\025\001\002\000\024\025\ufff3\032\ufff3\043\ufff3\044" +
    "\ufff3\046\ufff3\047\ufff3\050\ufff3\130\ufff3\133\ufff3\001\002" +
    "\000\024\025\ufff4\032\ufff4\043\ufff4\044\ufff4\046\ufff4\047" +
    "\ufff4\050\ufff4\130\ufff4\133\ufff4\001\002\000\004\002\000" +
    "\001\002\000\012\002\ufffd\025\ufffd\032\ufffd\050\ufffd\001" +
    "\002\000\016\043\006\044\005\047\012\050\ufffb\130\015" +
    "\133\011\001\002\000\004\026\050\001\002\000\004\127" +
    "\051\001\002\000\004\106\052\001\002\000\004\127\053" +
    "\001\002\000\016\043\ufff2\044\ufff2\047\ufff2\050\ufff2\130" +
    "\ufff2\133\ufff2\001\002\000\004\050\055\001\002\000\024" +
    "\002\ufff6\025\ufff6\032\ufff6\043\ufff6\044\ufff6\047\ufff6\050" +
    "\ufff6\130\ufff6\133\ufff6\001\002\000\004\046\057\001\002" +
    "\000\016\043\006\044\005\047\012\050\ufffb\130\015\133" +
    "\011\001\002\000\004\050\061\001\002\000\024\002\ufff5" +
    "\025\ufff5\032\ufff5\043\ufff5\044\ufff5\047\ufff5\050\ufff5\130" +
    "\ufff5\133\ufff5\001\002\000\012\002\ufffe\025\ufffe\032\ufffe" +
    "\050\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\060\000\016\002\007\003\012\004\015\010\013\011" +
    "\003\013\006\001\001\000\014\003\061\004\015\010\013" +
    "\011\003\013\006\001\001\000\006\006\055\007\023\001" +
    "\001\000\004\012\045\001\001\000\014\003\044\004\015" +
    "\010\013\011\003\013\006\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\006\025\007\023\001\001\000\002" +
    "\001\001\000\014\003\021\004\015\010\013\011\003\013" +
    "\006\001\001\000\002\001\001\000\014\003\016\004\015" +
    "\010\013\011\003\013\006\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\003" +
    "\026\004\015\010\013\011\003\013\006\001\001\000\004" +
    "\005\031\001\001\000\014\003\036\004\015\010\013\011" +
    "\003\013\006\001\001\000\006\006\033\007\023\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\003\034\004" +
    "\015\010\013\011\003\013\006\001\001\000\004\005\035" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\007" +
    "\042\001\001\000\004\007\041\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\003\053\004\015\010\013\011\003\013\006\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\003\057\004\015\010" +
    "\013\011\003\013\006\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$RubyParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$RubyParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$RubyParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




	

    /**Método que é chamado automaticamente antes de um erro de sintaxe.*/
    public void syntax_error(Symbol s){
        System.out.println("Erro na linha " + (s.right+1) +", Coluna "+s.left+ ". ID "
        +s.value + " não reconhecido." );
    }

    /**Método que é chamado quando não é possível a recuperação de erros.*/
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.out.println("Falha na compilação.");
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$RubyParser$actions {


/** Aqui podemos adicionar código JAVA */

  private final RubyParser parser;

  /** Constructor */
  CUP$RubyParser$actions(RubyParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$RubyParser$do_action(
    int                        CUP$RubyParser$act_num,
    java_cup.runtime.lr_parser CUP$RubyParser$parser,
    java.util.Stack            CUP$RubyParser$stack,
    int                        CUP$RubyParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$RubyParser$result;

      /* select the action based on the action number */
      switch (CUP$RubyParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // variavel ::= STRING 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("variavel",6, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // variavel ::= IDENTIFICADOR ATRIBUICAO NUMERO 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("variavel",6, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-2)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // arg ::= NUMERO 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("arg",5, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // arg ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("arg",5, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr_for ::= IDENTIFICADOR IN NUMERO DOIS_PONTOS2 NUMERO 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("expr_for",8, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-4)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expr ::= arg MENOR arg 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("expr",4, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-2)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // expr ::= arg MAIOR arg 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("expr",4, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-2)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // repeticao_while ::= WHILE expr DO codigo END_MINUSCULO 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("repeticao_while",9, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-4)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // repeticao_for ::= FOR expr_for codigo END_MINUSCULO 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("repeticao_for",7, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-3)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // cod_condicao ::= 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("cod_condicao",3, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // cod_condicao ::= ELSE codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("cod_condicao",3, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // cod_condicao ::= ELSIF expr codigo cod_condicao 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("cod_condicao",3, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-3)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // condicao ::= IF expr codigo cod_condicao END_MINUSCULO 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("condicao",2, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-4)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // codigo ::= 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // codigo ::= variavel codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // codigo ::= repeticao_while codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // codigo ::= repeticao_for codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // codigo ::= condicao codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;
		RESULT = start_val;
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$RubyParser$parser.done_parsing();
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

