
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 17 16:27:21 BRT 2015
//----------------------------------------------------

package sintatico;

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Nov 17 16:27:21 BRT 2015
  */
public class RubyParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public RubyParser() {super();}

  /** Constructor which sets the default scanner. */
  public RubyParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public RubyParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\052\000\002\002\003\000\002\002\004\000\002\003" +
    "\004\000\002\003\004\000\002\003\004\000\002\003\004" +
    "\000\002\003\004\000\002\003\004\000\002\003\002\000" +
    "\002\017\002\000\002\004\010\000\002\005\006\000\002" +
    "\005\004\000\002\005\002\000\002\020\002\000\002\011" +
    "\007\000\002\021\002\000\002\022\002\000\002\013\011" +
    "\000\002\023\002\000\002\015\012\000\002\024\002\000" +
    "\002\014\007\000\002\025\002\000\002\006\006\000\002" +
    "\026\002\000\002\006\006\000\002\027\002\000\002\030" +
    "\002\000\002\031\002\000\002\032\002\000\002\012\013" +
    "\000\002\033\002\000\002\034\002\000\002\016\007\000" +
    "\002\016\003\000\002\007\003\000\002\007\003\000\002" +
    "\035\002\000\002\036\002\000\002\010\007\000\002\010" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\122\000\022\002\ufff9\041\022\042\015\043\006\044" +
    "\005\047\014\130\020\133\013\001\002\000\030\002\ufff9" +
    "\025\ufff9\032\ufff9\041\022\042\015\043\006\044\005\047" +
    "\014\050\ufff9\130\020\133\013\001\002\000\006\127\ufff1" +
    "\130\ufff1\001\002\000\004\130\ufff3\001\002\000\030\002" +
    "\ufff9\025\ufff9\032\ufff9\041\022\042\015\043\006\044\005" +
    "\047\014\050\ufff9\130\020\133\013\001\002\000\030\002" +
    "\ufff9\025\ufff9\032\ufff9\041\022\042\015\043\006\044\005" +
    "\047\014\050\ufff9\130\020\133\013\001\002\000\030\002" +
    "\ufff9\025\ufff9\032\ufff9\041\022\042\015\043\006\044\005" +
    "\047\014\050\ufff9\130\020\133\013\001\002\000\004\002" +
    "\075\001\002\000\030\002\uffd8\025\uffd8\032\uffd8\041\uffd8" +
    "\042\uffd8\043\uffd8\044\uffd8\047\uffd8\050\uffd8\130\uffd8\133" +
    "\uffd8\001\002\000\006\127\051\130\053\001\002\000\004" +
    "\130\uffee\001\002\000\004\002\001\001\002\000\030\002" +
    "\ufff9\025\ufff9\032\ufff9\041\022\042\015\043\006\044\005" +
    "\047\014\050\ufff9\130\020\133\013\001\002\000\004\110" +
    "\uffdb\001\002\000\030\002\ufff9\025\ufff9\032\ufff9\041\022" +
    "\042\015\043\006\044\005\047\014\050\ufff9\130\020\133" +
    "\013\001\002\000\004\130\uffec\001\002\000\004\130\024" +
    "\001\002\000\022\041\022\042\015\043\006\044\005\047" +
    "\014\050\ufff9\130\020\133\013\001\002\000\004\050\026" +
    "\001\002\000\030\002\uffeb\025\uffeb\032\uffeb\041\uffeb\042" +
    "\uffeb\043\uffeb\044\uffeb\047\uffeb\050\uffeb\130\uffeb\133\uffeb" +
    "\001\002\000\012\002\uffff\025\uffff\032\uffff\050\uffff\001" +
    "\002\000\004\110\031\001\002\000\004\127\uffda\001\002" +
    "\000\004\127\033\001\002\000\030\002\uffd9\025\uffd9\032" +
    "\uffd9\041\uffd9\042\uffd9\043\uffd9\044\uffd9\047\uffd9\050\uffd9" +
    "\130\uffd9\133\uffd9\001\002\000\012\002\ufffa\025\ufffa\032" +
    "\ufffa\050\ufffa\001\002\000\004\130\036\001\002\000\004" +
    "\051\037\001\002\000\004\130\040\001\002\000\006\052" +
    "\uffde\103\uffe1\001\002\000\004\052\042\001\002\000\022" +
    "\041\022\042\015\043\006\044\005\047\014\050\ufff9\130" +
    "\020\133\013\001\002\000\004\050\044\001\002\000\030" +
    "\002\uffed\025\uffed\032\uffed\041\uffed\042\uffed\043\uffed\044" +
    "\uffed\047\uffed\050\uffed\130\uffed\133\uffed\001\002\000\004" +
    "\103\046\001\002\000\004\130\uffe0\001\002\000\004\130" +
    "\040\001\002\000\004\052\uffdf\001\002\000\034\025\uffdc" +
    "\032\uffdc\041\uffdc\042\uffdc\043\uffdc\044\uffdc\046\uffdc\047" +
    "\uffdc\050\uffdc\073\uffdc\074\uffdc\130\uffdc\133\uffdc\001\002" +
    "\000\006\073\070\074\067\001\002\000\034\025\uffdd\032" +
    "\uffdd\041\uffdd\042\uffdd\043\uffdd\044\uffdd\046\uffdd\047\uffdd" +
    "\050\uffdd\073\uffdd\074\uffdd\130\uffdd\133\uffdd\001\002\000" +
    "\026\025\ufff9\032\ufff9\041\022\042\015\043\006\044\005" +
    "\047\014\050\ufff9\130\020\133\013\001\002\000\010\025" +
    "\ufff8\032\ufff8\050\ufff8\001\002\000\010\025\057\032\060" +
    "\050\ufff4\001\002\000\022\041\022\042\015\043\006\044" +
    "\005\047\014\050\ufff9\130\020\133\013\001\002\000\006" +
    "\127\051\130\053\001\002\000\004\050\062\001\002\000" +
    "\030\002\ufff7\025\ufff7\032\ufff7\041\ufff7\042\ufff7\043\ufff7" +
    "\044\ufff7\047\ufff7\050\ufff7\130\ufff7\133\ufff7\001\002\000" +
    "\026\025\ufff9\032\ufff9\041\022\042\015\043\006\044\005" +
    "\047\014\050\ufff9\130\020\133\013\001\002\000\010\025" +
    "\057\032\060\050\ufff4\001\002\000\004\050\ufff6\001\002" +
    "\000\004\050\ufff5\001\002\000\006\127\uffea\130\uffea\001" +
    "\002\000\006\127\uffe8\130\uffe8\001\002\000\006\127\051" +
    "\130\053\001\002\000\030\025\uffe7\032\uffe7\041\uffe7\042" +
    "\uffe7\043\uffe7\044\uffe7\046\uffe7\047\uffe7\050\uffe7\130\uffe7" +
    "\133\uffe7\001\002\000\006\127\051\130\053\001\002\000" +
    "\030\025\uffe9\032\uffe9\041\uffe9\042\uffe9\043\uffe9\044\uffe9" +
    "\046\uffe9\047\uffe9\050\uffe9\130\uffe9\133\uffe9\001\002\000" +
    "\004\002\000\001\002\000\012\002\ufffc\025\ufffc\032\ufffc" +
    "\050\ufffc\001\002\000\012\002\ufffd\025\ufffd\032\ufffd\050" +
    "\ufffd\001\002\000\012\002\ufffb\025\ufffb\032\ufffb\050\ufffb" +
    "\001\002\000\004\130\102\001\002\000\004\026\uffe6\001" +
    "\002\000\022\041\022\042\015\043\006\044\005\047\014" +
    "\050\ufff9\130\020\133\013\001\002\000\004\050\105\001" +
    "\002\000\030\002\ufff2\025\ufff2\032\ufff2\041\ufff2\042\ufff2" +
    "\043\ufff2\044\ufff2\047\ufff2\050\ufff2\130\ufff2\133\ufff2\001" +
    "\002\000\004\026\107\001\002\000\004\127\uffe5\001\002" +
    "\000\004\127\111\001\002\000\004\106\uffe4\001\002\000" +
    "\004\106\113\001\002\000\004\127\uffe3\001\002\000\004" +
    "\127\115\001\002\000\022\041\uffe2\042\uffe2\043\uffe2\044" +
    "\uffe2\047\uffe2\050\uffe2\130\uffe2\133\uffe2\001\002\000\006" +
    "\127\051\130\053\001\002\000\004\046\120\001\002\000" +
    "\022\041\ufff0\042\ufff0\043\ufff0\044\ufff0\047\ufff0\050\ufff0" +
    "\130\ufff0\133\ufff0\001\002\000\022\041\022\042\015\043" +
    "\006\044\005\047\014\050\ufff9\130\020\133\013\001\002" +
    "\000\004\050\123\001\002\000\030\002\uffef\025\uffef\032" +
    "\uffef\041\uffef\042\uffef\043\uffef\044\uffef\047\uffef\050\uffef" +
    "\130\uffef\133\uffef\001\002\000\012\002\ufffe\025\ufffe\032" +
    "\ufffe\050\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\122\000\022\002\011\003\015\004\020\010\016\011" +
    "\003\013\007\014\006\015\010\001\001\000\020\003\123" +
    "\004\020\010\016\011\003\013\007\014\006\015\010\001" +
    "\001\000\004\021\115\001\001\000\004\020\100\001\001" +
    "\000\020\003\077\004\020\010\016\011\003\013\007\014" +
    "\006\015\010\001\001\000\020\003\076\004\020\010\016" +
    "\011\003\013\007\014\006\015\010\001\001\000\020\003" +
    "\075\004\020\010\016\011\003\013\007\014\006\015\010" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\006" +
    "\053\007\051\001\001\000\004\023\034\001\001\000\002" +
    "\001\001\000\020\003\033\004\020\010\016\011\003\013" +
    "\007\014\006\015\010\001\001\000\004\035\027\001\001" +
    "\000\020\003\026\004\020\010\016\011\003\013\007\014" +
    "\006\015\010\001\001\000\004\024\022\001\001\000\002" +
    "\001\001\000\020\003\024\004\020\010\016\011\003\013" +
    "\007\014\006\015\010\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\036" +
    "\031\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\016" +
    "\040\001\001\000\004\033\044\001\001\000\002\001\001" +
    "\000\020\003\042\004\020\010\016\011\003\013\007\014" +
    "\006\015\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\034\046\001\001\000\004\016" +
    "\047\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\003\054\004\020\010" +
    "\016\011\003\013\007\014\006\015\010\001\001\000\004" +
    "\017\055\001\001\000\004\005\060\001\001\000\020\003" +
    "\065\004\020\010\016\011\003\013\007\014\006\015\010" +
    "\001\001\000\006\006\062\007\051\001\001\000\002\001" +
    "\001\000\002\001\001\000\020\003\063\004\020\010\016" +
    "\011\003\013\007\014\006\015\010\001\001\000\004\005" +
    "\064\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\025\072\001\001\000\004\026\070\001\001\000\004\007" +
    "\071\001\001\000\002\001\001\000\004\007\073\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\012\102\001\001" +
    "\000\004\027\105\001\001\000\020\003\103\004\020\010" +
    "\016\011\003\013\007\014\006\015\010\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\030" +
    "\107\001\001\000\002\001\001\000\004\031\111\001\001" +
    "\000\002\001\001\000\004\032\113\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\006\116\007\051\001\001" +
    "\000\002\001\001\000\004\022\120\001\001\000\020\003" +
    "\121\004\020\010\016\011\003\013\007\014\006\015\010" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$RubyParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$RubyParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$RubyParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




	

    /**Método que é chamado automaticamente antes de um erro de sintaxe.*/
    public void syntax_error(Symbol s){
        System.out.println("Erro na linha " + (s.right+1) +", Coluna "+s.left+ ". ID "
        +s.value + " não reconhecido." );
    }

    /**Método que é chamado quando não é possível a recuperação de erros.*/
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.out.println("Falha na compilação.");
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$RubyParser$actions {



  int inc = 0;

  public String quebraDeLinha(){
  
  	return "\n";
  
  }

  private final RubyParser parser;

  /** Constructor */
  CUP$RubyParser$actions(RubyParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$RubyParser$do_action(
    int                        CUP$RubyParser$act_num,
    java_cup.runtime.lr_parser CUP$RubyParser$parser,
    java.util.Stack            CUP$RubyParser$stack,
    int                        CUP$RubyParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$RubyParser$result;

      /* select the action based on the action number */
      switch (CUP$RubyParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // variavel ::= STRING 
            {
              Object RESULT =null;
		 System.out.println("STRING"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("variavel",6, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // variavel ::= IDENTIFICADOR NT$14 ATRIBUICAO NT$15 NUMERO 
            {
              Object RESULT =null;
              // propagate RESULT from NT$15
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;
		 System.out.println("NUMERO"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("variavel",6, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-4)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // NT$15 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;
 System.out.print(" = "); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$15",28, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // NT$14 ::= 
            {
              Object RESULT =null;
 System.out.print(" IDENTIFICADOR"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$14",27, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // arg ::= NUMERO 
            {
              Object RESULT =null;
		 System.out.print("NUMERO"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("arg",5, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // arg ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		 System.out.print("IDENTIFICADOR"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("arg",5, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // identificadores_funcao ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		 System.out.print(" IDENTIFICADOR"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("identificadores_funcao",12, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // identificadores_funcao ::= IDENTIFICADOR NT$12 VIRGULA NT$13 identificadores_funcao 
            {
              Object RESULT =null;
              // propagate RESULT from NT$13
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("identificadores_funcao",12, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-4)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // NT$13 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;
 System.out.print(", "); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$13",26, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // NT$12 ::= 
            {
              Object RESULT =null;
 System.out.print(" IDENTIFICADOR"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$12",25, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr_for ::= IDENTIFICADOR NT$8 IN NT$9 NUMERO NT$10 DOIS_PONTOS2 NT$11 NUMERO 
            {
              Object RESULT =null;
              // propagate RESULT from NT$11
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;
		 System.out.print("NUMERO \n"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("expr_for",8, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-8)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // NT$11 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;
 System.out.print(" .. "); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$11",24, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // NT$10 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;
 System.out.print(" NUMERO"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$10",23, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // NT$9 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;
 System.out.print(" IN "); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$9",22, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // NT$8 ::= 
            {
              Object RESULT =null;
 System.out.print(" IDENTIFICADOR "); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$8",21, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= arg MENOR NT$7 arg 
            {
              Object RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("expr",4, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-3)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // NT$7 ::= 
            {
              Object RESULT =null;
 System.out.print(" < "); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$7",20, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr ::= arg MAIOR NT$6 arg 
            {
              Object RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("expr",4, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-3)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // NT$6 ::= 
            {
              Object RESULT =null;
 System.out.print(" > "); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$6",19, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // classe ::= CLASS NT$5 IDENTIFICADOR codigo END_MINUSCULO 
            {
              Object RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-3)).value;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("classe",10, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-4)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // NT$5 ::= 
            {
              Object RESULT =null;
 System.out.print("CLASS "); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$5",18, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // funcao ::= DEF NT$4 IDENTIFICADOR PARENTESE_ABERTURA identificadores_funcao PARENTESE_FECHAMENTO codigo END_MINUSCULO 
            {
              Object RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-6)).value;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("funcao",11, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-7)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // NT$4 ::= 
            {
              Object RESULT =null;
 System.out.print("\nDEF"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$4",17, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // repeticao_while ::= WHILE NT$2 expr DO NT$3 codigo END_MINUSCULO 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-2)).value;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("repeticao_while",9, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-6)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // NT$3 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-2)).value;
 System.out.print("\n"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$3",16, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NT$2 ::= 
            {
              Object RESULT =null;
 System.out.print(" WHILE "); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$2",15, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // repeticao_for ::= FOR NT$1 expr_for codigo END_MINUSCULO 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-3)).value;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("repeticao_for",7, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-4)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // NT$1 ::= 
            {
              Object RESULT =null;
 System.out.print("FOR"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$1",14, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // cod_condicao ::= 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("cod_condicao",3, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // cod_condicao ::= ELSE codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("cod_condicao",3, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // cod_condicao ::= ELSIF expr codigo cod_condicao 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("cod_condicao",3, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-3)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // condicao ::= IF expr codigo NT$0 cod_condicao END_MINUSCULO 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-2)).value;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("condicao",2, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-5)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NT$0 ::= 
            {
              Object RESULT =null;
 System.out.println("CONDIÇÃO"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("NT$0",13, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // codigo ::= 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // codigo ::= variavel codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // codigo ::= classe codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // codigo ::= funcao codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // codigo ::= repeticao_while codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // codigo ::= repeticao_for codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // codigo ::= condicao codigo 
            {
              Object RESULT =null;

              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("codigo",1, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)).value;
		RESULT = start_val;
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.elementAt(CUP$RubyParser$top-1)), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$RubyParser$parser.done_parsing();
          return CUP$RubyParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= codigo 
            {
              Object RESULT =null;
		 System.out.print("\n"); 
              CUP$RubyParser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RubyParser$stack.peek()), RESULT);
            }
          return CUP$RubyParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

