
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Nov 02 15:20:16 GMT-03:00 2015
//----------------------------------------------------

package sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PORCENTAGEM = 52;
  public static final int PARENTESE_FECHAMENTO = 41;
  public static final int IDENTIFICADOR = 88;
  public static final int PONTENCIACAO_IGUAL = 82;
  public static final int BARRA = 50;
  public static final int E_COMERCIAL_IGUAL = 80;
  public static final int INCREMENTO_MULTIP = 76;
  public static final int TIL = 58;
  public static final int VIRGULA = 67;
  public static final int VEZES = 48;
  public static final int UNTIL = 36;
  public static final int BARRA_VERTICAL_IGUAL = 81;
  public static final int CHAVE_ABERTURA = 42;
  public static final int NEXT = 28;
  public static final int MENOR_MENOR = 53;
  public static final int ELSIF = 24;
  public static final int ATRIBUICAO = 72;
  public static final int PORCENTAGEM_IGUAL = 79;
  public static final int NUMERO = 87;
  public static final int MULTIP_MULTIP_IGUAL = 85;
  public static final int IGUAL_IGUAL = 63;
  public static final int YIELD = 15;
  public static final int FALSE = 8;
  public static final int NOT = 9;
  public static final int COMENTARIO = 86;
  public static final int DEF = 33;
  public static final int SELF = 5;
  public static final int DIFERENTE2 = 65;
  public static final int DEFINED = 12;
  public static final int DIFERENTE1 = 64;
  public static final int UNDEF = 22;
  public static final int THEN = 14;
  public static final int DOIS_PONTOS = 68;
  public static final int POTENCIACAO = 57;
  public static final int PUTS = 90;
  public static final int ARROBA = 66;
  public static final int BARRA_BARRA = 51;
  public static final int WHEN = 6;
  public static final int CLASS = 32;
  public static final int INCREMENTO = 74;
  public static final int SUPER = 10;
  public static final int UNLESS = 27;
  public static final int ALIAS = 11;
  public static final int TRUE = 18;
  public static final int CHAVE_FECHAMENTO = 43;
  public static final int PONTO_E_VIRGULA = 73;
  public static final int TIPO2 = 89;
  public static final int END_MINUSCULO = 39;
  public static final int PONTO = 69;
  public static final int WHILE = 35;
  public static final int NUMERO_TERMINAL = 92;
  public static final int MODULE = 25;
  public static final int REDO = 17;
  public static final int DO = 37;
  public static final int FOR = 34;
  public static final int DECREMENTO = 75;
  public static final int RETURN = 29;
  public static final int BEGIN_MINUSCULO = 30;
  public static final int ELSE = 19;
  public static final int MENOS = 47;
  public static final int MENOR = 59;
  public static final int COLCHETE_ABERTURA = 44;
  public static final int BREAK = 23;
  public static final int MENOR_OU_IGUAL = 61;
  public static final int MAIOR_MAIOR_IGUAL = 83;
  public static final int PARENTESE_ABERTURA = 40;
  public static final int MAIOR = 60;
  public static final int EOF = 0;
  public static final int APOSTROFO = 71;
  public static final int DOIS_PONTOS2 = 70;
  public static final int BEGIN_MAIUSCULO = 2;
  public static final int RESCUE = 21;
  public static final int MAIS = 46;
  public static final int MAIOR_MAIOR = 54;
  public static final int END_MAIUSCULO = 7;
  public static final int BARRA_VERTICAL = 56;
  public static final int IN = 20;
  public static final int OR = 13;
  public static final int error = 1;
  public static final int INCREMENTO_DIVISAO = 77;
  public static final int MAIOR_OU_IGUAL = 62;
  public static final int IF = 38;
  public static final int E_COMERCIAL = 55;
  public static final int ASSERT = 4;
  public static final int COLCHETE_FECHAMENTO = 45;
  public static final int CASE = 31;
  public static final int STRING = 91;
  public static final int RETRY = 26;
  public static final int AND = 16;
  public static final int PALAVRA = 93;
  public static final int ENSURE = 3;
  public static final int MENOR_MENOR_IGUAL = 84;
  public static final int INCREMENTO_DIVISAO_DIVISAO = 78;
  public static final int VEZES_VEZES = 49;
}

